### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by domesya** [Stazed/nonlib-xt#2]
I apologize in advance if this issue is hilariously stupid and completely out of the scope but I've been unable to compile nonlib. When trying to compile it I get errors. The first of which is:
```
In file included from /home/domesya/Downloads/git/non-mixer-xt/nonlib/JACK/Client.H:28,                                                                                   
                 from /home/domesya/Downloads/git/non-mixer-xt/nonlib/JACK/Client.C:20:                                                                                   
/home/domesya/Downloads/git/non-mixer-xt/nonlib/JACK/../nonlib/Mutex.H:24:44: error: 'PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP' was not declared in this scope; did you mean 'PTHREAD_MUTEX_INITIALIZER'?                                                                                                                                             
   24 | const pthread_mutex_t _mutex_initializer = PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP;                                                                                
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                 
      |                                            PTHREAD_MUTEX_INITIALIZER                                                                                              
make[2]: *** [mixer/CMakeFiles/non-mixer-xt.dir/build.make:76: mixer/CMakeFiles/non-mixer-xt.dir/__/nonlib/JACK/Client.C.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:181: mixer/CMakeFiles/non-mixer-xt.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

I've been unable to compile nonlib and in effect unable to compile non-mixer-xt and non-timeline-xt both of which are great projects I've been searching for ages. Is there something wrong with the code or is there something wrong with my system?
Appreciate any help in advance.

**Comment by Stazed** [comment]
Is pthread.h installed on your system? Usually located /usr/include/pthread.h.

If not, then you need to install it.  If so, then more information is needed.

Like what distribution are you using?

Is this a new install or are you updating? 

Did you run git submodule update --init?

Are you getting the same error for non-timeline-xt?

**Comment by domesya** [comment]
I think I figured it out. I tested installing it on Arch Linux with glibc and it worked flawlessly while before i was trying to compile it on Void Linux with musl and FreeBSD with it's own libc, both of which gave me the same errors. So I think it definetely has to do something with having something else instead of glibc. After doing some web scraping I found out that the most likely solution is to explicitly link libc, which I've been unable to do since I'm not a developer and I have no idea about even basic programming concepts.
Appreciate your quick response and will to help even with something like that.

**Comment by Stazed** [comment]
pthread.h is from GNU libc and and not musl. The Void Linux site says that GNU is also supported. You could probably get Void Linux to work by switching. As for FreeBSD, I would be surprised if it worked even if you did get it to compile.

**Comment by domesya** [comment]
Looks like I'll have to switch. Welp thanks for help and sorry for bother. That aside I really appreciate the work you put in those projects. Using Non stuff is my favourite way to make music and thanks to you I'll be able to continue making music using those fantastic tools while being able to make use of more modern plugins.
